dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  flutter_overlay_window: ^0.4.5  # ফ্লোটিং অবতারের জন্য

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ragna_avatar.png
    - assets/icons/maya_avatar.png
