name: siam_ai_app
description: "Siam AI Video & Voice Assistant with YouTube Interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  # অ্যানিমে ক্যারেক্টার ও আইকনের ফোল্ডার এখানে পারফেক্টলি যুক্ত করা হলো
  assets:
    - assets/icons/
    - assets/images/
